# Generated by Django 5.2 on 2025-04-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('non_binary', 'Não-Binário'), ('other', 'Outro')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipCode', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client.client')),
            ],
        ),
    ]
