# Generated by Django 5.2 on 2025-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('separated', 'Separado(a)')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
